### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Warrior996** [doublecheckhjc/Image-classification_1#1]
你好，请问能否提供一下数据集？

**Comment by doublecheckhjc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doublecheckhjc/Image-classification_1"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 晚上7:20
收件人:&nbsp;"doublecheckhjc/Image-classification_1"<Image-classification_1@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[doublecheckhjc/Image-classification_1] 数据集 (#1)





 
你好，请问能否提供一下数据集？

**Comment by Warrior996** [comment]
你好，请问上一封回复什么意思？

**Comment by doublecheckhjc** [comment]
上一封我发了两个文件，说是文件太大邮件投递失败，所以又发了一封




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doublecheckhjc/Image-classification_1"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 上午9:07
收件人:&nbsp;"doublecheckhjc/Image-classification_1"<Image-classification_1@noreply.github.com&gt;;
抄送:&nbsp;"韩金城"<1012850074@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [doublecheckhjc/Image-classification_1] 数据集 (#1)





 
你好，请问上一封回复什么意思？

**Comment by Warrior996** [comment]
不好意思，我这里没有收到，麻烦您发下邮箱   820126751@qq.com  谢谢

**Comment by babatur** [comment]
你好  请问能否发一下数据集  1768777219@qq.com

**Comment by Warrior996** [comment]
你好，建议向作者索要，若作者长期不回复，可再联系我。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doublecheckhjc/Image-classification_1"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 下午3:03
收件人:&nbsp;"doublecheckhjc/Image-classification_1"<Image-classification_1@noreply.github.com&gt;;
抄送:&nbsp;"陈凯"<chen_kaii@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [doublecheckhjc/Image-classification_1] 数据集 (#1)





 
你好  请问能否发一下数据集  1768777219@qq.com

**Comment by axu999** [comment]
请问可以提供一下数据集吗

**Comment by axu999** [comment]
请问可以提供一下数据集吗2605668864@qq.com
